theme: jekyll-theme-minimal
title: Artem's profile on GitHub
description: Artem Nechunaev is Engineering Manager & Senior Software Engineer with 15+ years of experience building scalable, high-quality web products.
